/* openbim-ifc C ABI v0.1 -- see openbim-ifc-capi/README.md for the ownership protocol. */

#ifndef OPENBIM_IFC_CAPI_V0_1_H
#define OPENBIM_IFC_CAPI_V0_1_H

#pragma once

/* Generated by cbindgen from openbim-ifc-capi; do not edit. Regenerate with UPDATE_HEADER=1 cargo test -p openbim-ifc-capi --test header. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Binary digits in the string range.
 */
#define OPENBIM_IFC_KIND_BINARY 7

/**
 * `.T.`/`.F.`; `int_value` is 1 or 0.
 */
#define OPENBIM_IFC_KIND_BOOL 2

/**
 * `*`.
 */
#define OPENBIM_IFC_KIND_DERIVED 1

/**
 * Enumeration name in the string range.
 */
#define OPENBIM_IFC_KIND_ENUM 8

/**
 * Integer in `int_value`.
 */
#define OPENBIM_IFC_KIND_INTEGER 4

/**
 * Aggregate; `child_count` children follow.
 */
#define OPENBIM_IFC_KIND_LIST 10

/**
 * Kind codes. Plain integers, not a Rust enum, so an unknown value from C
 * is rejected rather than read as an invalid discriminant.
 */
#define OPENBIM_IFC_KIND_NULL 0

/**
 * Finite real in `real_value`.
 */
#define OPENBIM_IFC_KIND_REAL 5

/**
 * Entity id in `int_value` (non-negative).
 */
#define OPENBIM_IFC_KIND_REF 9

/**
 * Text in the string range.
 */
#define OPENBIM_IFC_KIND_TEXT 6

/**
 * Typed wrapper; type name in the string range, one child follows.
 */
#define OPENBIM_IFC_KIND_TYPED 11

/**
 * `.U.`.
 */
#define OPENBIM_IFC_KIND_UNKNOWN 3

/**
 * Result of every ABI call. `Ok` is zero; every failure is non-zero.
 *
 * The values from `Parse` to `UnsupportedSchema` are the binding errors
 * shared with the JavaScript and Python bindings; the rest describe misuse
 * of the C boundary itself.
 */
enum OpenbimIfcStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Success.
   */
  OPENBIM_IFC_STATUS_OK = 0,
  /**
   * A required pointer was null.
   */
  OPENBIM_IFC_STATUS_NULL_POINTER = 1,
  /**
   * An argument was malformed (bad UTF-8, a malformed value tape, ...).
   */
  OPENBIM_IFC_STATUS_INVALID_ARGUMENT = 2,
  /**
   * The model handle is zero, stale, or already destroyed.
   */
  OPENBIM_IFC_STATUS_INVALID_HANDLE = 3,
  /**
   * The output buffer is smaller than `*out_required`.
   */
  OPENBIM_IFC_STATUS_BUFFER_TOO_SMALL = 4,
  /**
   * The STEP input could not be parsed (`parse`).
   */
  OPENBIM_IFC_STATUS_PARSE = 10,
  /**
   * The model could not be serialized (`write`).
   */
  OPENBIM_IFC_STATUS_WRITE = 11,
  /**
   * No entity has the given id (`missing-entity`).
   */
  OPENBIM_IFC_STATUS_MISSING_ENTITY = 12,
  /**
   * A value did not follow the encoding (`invalid-value`).
   */
  OPENBIM_IFC_STATUS_INVALID_VALUE = 13,
  /**
   * An id or index is outside the representable range (`out-of-range`).
   */
  OPENBIM_IFC_STATUS_OUT_OF_RANGE = 14,
  /**
   * The file's schema is not bundled (`unsupported-schema`).
   */
  OPENBIM_IFC_STATUS_UNSUPPORTED_SCHEMA = 15,
  /**
   * The requested value does not exist (no schema token, no error, ...).
   */
  OPENBIM_IFC_STATUS_NO_VALUE = 20,
  /**
   * A Rust panic was contained at the boundary. Report it as a bug.
   */
  OPENBIM_IFC_STATUS_PANIC = 255,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum OpenbimIfcStatus OpenbimIfcStatus;
#else
typedef int32_t OpenbimIfcStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Opaque model handle. Zero is never a valid handle.
 */
typedef uint64_t OpenbimIfcModel;

/**
 * One node of a value tape. Fields a kind does not use are zero.
 */
typedef struct {
  /**
   * One of the `OPENBIM_IFC_KIND_*` codes.
   */
  int32_t kind;
  /**
   * Children following a `list` node; 0 otherwise.
   */
  uint32_t child_count;
  /**
   * Payload of `bool` (0/1), `integer` and `ref`.
   */
  int64_t int_value;
  /**
   * Payload of `real`.
   */
  double real_value;
  /**
   * Byte offset of this node's string in the string buffer.
   */
  uint64_t str_offset;
  /**
   * Byte length of this node's string (no NUL terminator).
   */
  uint64_t str_len;
} OpenbimIfcValueNode;

/**
 * ABI and crate versions, reported separately: the ABI version changes only
 * when the C surface does, the crate version on every release.
 */
typedef struct {
  /**
   * ABI major; also the `v0_1` in every symbol name.
   */
  uint16_t abi_major;
  /**
   * ABI minor.
   */
  uint16_t abi_minor;
  /**
   * ABI patch.
   */
  uint16_t abi_patch;
  /**
   * Crate major.
   */
  uint16_t crate_major;
  /**
   * Crate minor.
   */
  uint16_t crate_minor;
  /**
   * Crate patch.
   */
  uint16_t crate_patch;
} OpenbimIfcVersion;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Append an entity of `type_name` whose `attribute_count` attributes are
 * on the tape back to back, and write its new id to `out_id`.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_entity_set_attribute`]; `type_name` valid for
 * `type_len` reads; `out_id` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_add(OpenbimIfcModel model,
                                             const uint8_t *type_name,
                                             size_t type_len,
                                             size_t attribute_count,
                                             const OpenbimIfcValueNode *nodes,
                                             size_t node_count,
                                             const uint8_t *strings,
                                             size_t string_len,
                                             uint64_t *out_id);

/**
 * Attribute `index` of entity `id` as a value tape (`$` past the end).
 *
 * # Safety
 * As for `fill_tape`: each buffer null with capacity 0, or valid for its
 * capacity; both `out_*_required` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_attribute(OpenbimIfcModel model,
                                                   uint64_t id,
                                                   size_t index,
                                                   OpenbimIfcValueNode *nodes,
                                                   size_t node_capacity,
                                                   size_t *out_nodes_required,
                                                   uint8_t *strings,
                                                   size_t string_capacity,
                                                   size_t *out_strings_required);

/**
 * Every attribute of entity `id`, back to back on one tape, plus how many
 * top-level values it holds.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_entity_attribute`]; `out_count` valid for one
 * write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_attributes(OpenbimIfcModel model,
                                                    uint64_t id,
                                                    size_t *out_count,
                                                    OpenbimIfcValueNode *nodes,
                                                    size_t node_capacity,
                                                    size_t *out_nodes_required,
                                                    uint8_t *strings,
                                                    size_t string_capacity,
                                                    size_t *out_strings_required);

/**
 * Remove entity `id`; references to it are left dangling.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_remove(OpenbimIfcModel model, uint64_t id);

/**
 * Set attribute `index` of entity `id` from a one-value tape. Writing past
 * the end pads the gap with `$`.
 *
 * # Safety
 * `nodes` must be valid for `node_count` reads and `strings` for
 * `string_len` reads (either may be null when its length is 0).
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_set_attribute(OpenbimIfcModel model,
                                                       uint64_t id,
                                                       size_t index,
                                                       const OpenbimIfcValueNode *nodes,
                                                       size_t node_count,
                                                       const uint8_t *strings,
                                                       size_t string_len);

/**
 * The type name of entity `id`, upper-case, NUL-terminated.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_write`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_type(OpenbimIfcModel model,
                                              uint64_t id,
                                              uint8_t *buffer,
                                              size_t capacity,
                                              size_t *out_required);

/**
 * The last error on `model` as its stable code (`parse`, `missing-entity`,
 * ...), NUL-terminated; `NoValue` if the last call succeeded.
 *
 * # Safety
 * `buffer` must be null (with `capacity` 0) or valid for `capacity`
 * writes; `out_required` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_last_error_code(OpenbimIfcModel model,
                                                  uint8_t *buffer,
                                                  size_t capacity,
                                                  size_t *out_required);

/**
 * The last error on `model` as a human message, NUL-terminated; `NoValue`
 * if the last call succeeded.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_last_error_code`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_last_error_message(OpenbimIfcModel model,
                                                     uint8_t *buffer,
                                                     size_t capacity,
                                                     size_t *out_required);

/**
 * Number of live models, for leak checks.
 *
 * # Safety
 * `out_count` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_live_models(size_t *out_count);

/**
 * Create an empty model and write its handle to `out_model`.
 *
 * # Safety
 * `out_model` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_create(OpenbimIfcModel *out_model);

/**
 * Every dangling reference as `(from, to)` pairs, flattened: element
 * `2k` is a referencing id, `2k+1` the missing id it points to.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_ids`]; sizes count `u64`s, not pairs.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_dangling_references(OpenbimIfcModel model,
                                                            uint64_t *buffer,
                                                            size_t capacity,
                                                            size_t *out_required);

/**
 * Destroy a model. A stale or repeated handle is `InvalidHandle`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_destroy(OpenbimIfcModel model);

/**
 * Diagnostic `index` as a NUL-terminated string; `OutOfRange` past the end.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_write`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_diagnostic(OpenbimIfcModel model,
                                                   size_t index,
                                                   uint8_t *buffer,
                                                   size_t capacity,
                                                   size_t *out_required);

/**
 * Number of non-fatal parse diagnostics.
 *
 * # Safety
 * `out_count` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_diagnostic_count(OpenbimIfcModel model, size_t *out_count);

/**
 * Every entity id, in file order.
 *
 * # Safety
 * `buffer` must be null (with `capacity` 0) or valid for `capacity` `u64`
 * writes; `out_required` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_ids(OpenbimIfcModel model,
                                            uint64_t *buffer,
                                            size_t capacity,
                                            size_t *out_required);

/**
 * Ids of every entity of exactly `type_name` (UTF-8, `type_len` bytes,
 * case-insensitive). Subtypes are not included.
 *
 * # Safety
 * `type_name` must be valid for `type_len` reads; otherwise as for
 * [`openbim_ifc_v0_1_model_ids`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_ids_of_type(OpenbimIfcModel model,
                                                    const uint8_t *type_name,
                                                    size_t type_len,
                                                    uint64_t *buffer,
                                                    size_t capacity,
                                                    size_t *out_required);

/**
 * Ids of every entity of `type_name` or any of its subtypes, using the
 * schema the file's header declares. `UnsupportedSchema` if none is bundled.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_ids_of_type`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_ids_of_type_including_subtypes(OpenbimIfcModel model,
                                                                       const uint8_t *type_name,
                                                                       size_t type_len,
                                                                       uint64_t *buffer,
                                                                       size_t capacity,
                                                                       size_t *out_required);

/**
 * Number of entities.
 *
 * # Safety
 * `out_count` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_len(OpenbimIfcModel model, size_t *out_count);

/**
 * Parse `len` bytes of STEP and write the new model's handle.
 *
 * A parse failure has no model to hold its error, so the message is written
 * to the optional `error_buffer` (NUL-terminated, truncated to `capacity`).
 *
 * # Safety
 * `data` must be valid for `len` reads; `out_model` for one write;
 * `error_buffer`, if non-null, for `capacity` writes.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_parse(const uint8_t *data,
                                              size_t len,
                                              OpenbimIfcModel *out_model,
                                              uint8_t *error_buffer,
                                              size_t capacity);

/**
 * The first `FILE_SCHEMA` token as a NUL-terminated string, or `NoValue`.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_write`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_schema(OpenbimIfcModel model,
                                               uint8_t *buffer,
                                               size_t capacity,
                                               size_t *out_required);

/**
 * Serialize as STEP into a caller buffer; `out_required` gets the size.
 *
 * # Safety
 * `buffer` must be null (with `capacity` 0) or valid for `capacity`
 * writes; `out_required` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_write(OpenbimIfcModel model,
                                              uint8_t *buffer,
                                              size_t capacity,
                                              size_t *out_required);

/**
 * Write the ABI and crate versions.
 *
 * # Safety
 * `out_version` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_version(OpenbimIfcVersion *out_version);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPENBIM_IFC_CAPI_V0_1_H */
