//! Openings are subtracted in their host's frame, not in world coordinates
//! (#388).
//!
//! `flush_openings_site_placements.ifc` (generated by
//! `tools/gen_lowering_fixtures.py`) puts one wall, 3.65 x 0.25 x 3.67, with
//! two openings, 1.01 x 2.26, as deep as the wall is thick and flush with
//! both its faces, under four site placements: at the origin or at the
//! survey point (600 000, 5 600 000, 200), turned 2.3 degrees or not. In
//! world coordinates the georeferenced, turned case rounds the opening's
//! faces off the wall's by up to an ulp of 5.6e6, and the reference kernel
//! refuses the result as touching itself along the opening's edges. In the
//! wall's frame the coincidence the file states is kept.
//!
//! Three more walls cover the chain and the parts: `SIBLING`, whose openings
//! are placed relative to the site rather than the wall; `TWO_PART`, the
//! wall as two solids; and `ABSOLUTE`, whose openings share no placement
//! with the wall and are lowered in world coordinates as before.
#![cfg(feature = "compile-reference-backend")]

use std::path::PathBuf;

use axiolid_core::Tolerance;
use axiolid_mesh::TriMesh;
use axiolid_mesh_boolean_boolmesh::BoolmeshBoolean;
use axiolid_mesh_compile::ReferenceMeshCompiler;
use axiolid_model::{GeometryNode, SolidOperation};
use ifc_geometry::compile::{compile_product_mesh_net_with, compile_product_mesh_with};
use ifc_geometry::lower::{lower_product_net, LoweringSession};
use ifc_geometry::units;
use ifc_model::{Codec, EntityId, Model, Value};

/// The wall: 3.65 long, 0.25 thick, 3.67 high.
const GROSS: f64 = 3.65 * 0.25 * 3.67;
/// Two openings, each 1.01 x 2.26 through the wall's 0.25.
const OPENINGS: f64 = 2.0 * 1.01 * 2.26 * 0.25;
/// Volumes agree to a cubic millimetre: the meshes lie 5.6e6 m out, where
/// one ulp is about 1e-9 m.
const VOLUME_TOLERANCE: f64 = 1e-9;

/// The four site placements of the issue: origin or georeferenced, turned
/// or not. The wall carries its site's name.
const SITES: [&str; 4] = ["ORIGIN", "ORIGIN_TURNED", "GEOREF", "GEOREF_TURNED"];

fn fixture() -> Model {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test/fixtures/synthetic-lowering/flush_openings_site_placements.ifc");
    ifc_step::StepCodec
        .read_path(&path)
        .expect("fixture parses")
}

/// The kernel the issue reproduced with.
fn backend() -> ReferenceMeshCompiler<BoolmeshBoolean> {
    ReferenceMeshCompiler::new(BoolmeshBoolean)
}

/// The one entity of `type_name` whose `Name` (slot 2) is `name`.
fn named(model: &Model, type_name: &str, name: &str) -> EntityId {
    let found: Vec<EntityId> = model
        .of_type(type_name)
        .filter(|(_, entity)| matches!(entity.attributes.get(2), Some(Value::Text(text)) if text.as_ref() == name))
        .map(|(id, _)| id)
        .collect();
    assert_eq!(found.len(), 1, "exactly one {type_name} named {name}");
    found[0]
}

/// Divergence-theorem volume, summed about the first vertex for conditioning
/// (the georeferenced meshes lie 5.6e6 m out).
fn volume(mesh: &TriMesh) -> f64 {
    assert!(!mesh.indices.is_empty(), "compiled mesh is empty");
    let base = mesh.positions[0];
    mesh.indices
        .chunks_exact(3)
        .map(|t| {
            let [a, b, c] = [t[0], t[1], t[2]].map(|i| mesh.positions[i as usize] - base);
            a.dot(b.cross(c)) / 6.0
        })
        .sum()
}

/// The mesh's axis-aligned bounds, as `[min, max]`.
fn bounds(mesh: &TriMesh) -> [[f64; 3]; 2] {
    let mut out = [[f64::INFINITY; 3], [f64::NEG_INFINITY; 3]];
    for p in &mesh.positions {
        for (axis, value) in [p.x, p.y, p.z].into_iter().enumerate() {
            out[0][axis] = out[0][axis].min(value);
            out[1][axis] = out[1][axis].max(value);
        }
    }
    out
}

/// The wall's net mesh and its gross mesh, both through the world path.
fn net_and_gross(model: &Model, wall: &str) -> (TriMesh, TriMesh) {
    let host = named(model, "IFCWALL", wall);
    let net = compile_product_mesh_net_with(&backend(), model, host, Tolerance::MILLIMETRE)
        .unwrap_or_else(|error| panic!("{wall}: the net wall must mesh, got {error}"))
        .expect("the wall has a Body");
    assert_eq!(net.openings.len(), 2, "{wall}: both openings subtracted");
    let gross = compile_product_mesh_with(&backend(), model, host, Tolerance::MILLIMETRE)
        .unwrap_or_else(|error| panic!("{wall}: the gross wall must mesh, got {error}"))
        .expect("the wall has a Body");
    (net.mesh, gross)
}

/// Net = gross - both openings, and the net mesh lies where the gross one
/// does: in world coordinates, the openings inside the wall's outline.
fn assert_net(model: &Model, wall: &str) -> f64 {
    let (net, gross) = net_and_gross(model, wall);
    let (net_volume, gross_volume) = (volume(&net), volume(&gross));
    assert!(
        (gross_volume - GROSS).abs() < VOLUME_TOLERANCE,
        "{wall}: gross volume {gross_volume}, expected {GROSS}"
    );
    assert!(
        (net_volume - (GROSS - OPENINGS)).abs() < VOLUME_TOLERANCE,
        "{wall}: net volume {net_volume}, expected {}",
        GROSS - OPENINGS
    );
    let (net_box, gross_box) = (bounds(&net), bounds(&gross));
    for corner in 0..2 {
        for axis in 0..3 {
            let (a, b) = (net_box[corner][axis], gross_box[corner][axis]);
            assert!(
                (a - b).abs() < 1e-6,
                "{wall}: net bounds {net_box:?} are not the gross {gross_box:?}"
            );
        }
    }
    net_volume
}

/// The issue's table: the wall meshes at every site placement, and the net
/// volume is the gross less both openings. Before #388 the georeferenced,
/// turned wall was refused as touching itself along an opening's edge.
#[test]
fn flush_openings_mesh_at_every_site_placement() {
    let model = fixture();
    for wall in SITES {
        let net = assert_net(&model, wall);
        eprintln!("{wall}: net volume {net:.12}");
    }
}

/// Openings placed relative to the site, not the wall: the shared ancestor
/// is the site's placement, whose survey translation still cancels.
#[test]
fn openings_placed_beside_their_host_are_subtracted_in_its_frame() {
    let model = fixture();
    assert_net(&model, "SIBLING");
}

/// A host of two solids, each cut in the wall's frame, on the georeferenced
/// turned site: one Instance above the Collection of both parts' results.
#[test]
fn each_part_of_a_multi_part_host_is_cut_in_its_frame() {
    let model = fixture();
    assert_net(&model, "TWO_PART");
    let scale = units::resolve(&model);
    let mut session = LoweringSession::new(&model, &scale);
    let host = named(&model, "IFCWALL", "TWO_PART");
    let net = lower_product_net(&mut session, host)
        .expect("lowers")
        .expect("has a Body");
    let lowered = session.finish(net.root).expect("finishes");
    let Some(GeometryNode::Instance(instance)) = lowered.graph.get(lowered.root) else {
        panic!("the net root is not an Instance");
    };
    let Some(GeometryNode::Collection(parts)) = lowered.graph.get(instance.source) else {
        panic!("the Instance's source is not the Collection of parts");
    };
    assert_eq!(parts.len(), 2);
    for part in parts {
        assert!(
            matches!(
                lowered.graph.get(*part),
                Some(GeometryNode::SolidOperation(SolidOperation::Boolean { .. }))
            ),
            "each part is a Difference in the wall's frame"
        );
    }
}

/// The structure: the Difference nodes sit under one Instance carrying the
/// wall's world transform, for every site placement.
#[test]
fn the_difference_runs_under_one_instance_of_the_host_frame() {
    let model = fixture();
    let scale = units::resolve(&model);
    for wall in SITES.into_iter().chain(["SIBLING"]) {
        let mut session = LoweringSession::new(&model, &scale);
        let host = named(&model, "IFCWALL", wall);
        let net = lower_product_net(&mut session, host)
            .expect("lowers")
            .expect("has a Body");
        let lowered = session.finish(net.root).expect("finishes");
        let Some(GeometryNode::Instance(instance)) = lowered.graph.get(lowered.root) else {
            panic!("{wall}: the net root is not an Instance");
        };
        assert!(
            matches!(
                lowered.graph.get(instance.source),
                Some(GeometryNode::SolidOperation(SolidOperation::Boolean { .. }))
            ),
            "{wall}: the Instance's source is not the Difference"
        );
    }
}

/// No shared placement chain: the openings are absolute. Nothing is
/// guessed; the net body is lowered in world coordinates as before #388,
/// with the Difference at the root, and still nets correctly here, where
/// world is the site's frame at the origin.
#[test]
fn openings_without_a_shared_chain_keep_the_world_frame() {
    let model = fixture();
    let scale = units::resolve(&model);
    let mut session = LoweringSession::new(&model, &scale);
    let host = named(&model, "IFCWALL", "ABSOLUTE");
    let net = lower_product_net(&mut session, host)
        .expect("lowers")
        .expect("has a Body");
    let lowered = session.finish(net.root).expect("finishes");
    assert!(
        matches!(
            lowered.graph.get(lowered.root),
            Some(GeometryNode::SolidOperation(SolidOperation::Boolean { .. }))
        ),
        "the fallback's root is the world-frame Difference itself"
    );
    assert_net(&model, "ABSOLUTE");
}
