[package]
name = "ifc-classification"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
license = "AGPL-3.0-or-later"
authors = ["point-grey"]
repository = "https://github.com/openbimrs/ifc"
description = "Classification systems, document references, libraries, external references."

[dependencies]
ifc-schema.workspace = true
ifc-model.workspace = true
