//! `crates/openbim-ifc-capi/include/openbim_ifc.h`: every function, type,
//! constant and status code, as the C API reference page (`docs/api/c.md`).
//!
//! The header is generated by cbindgen from the Rust exports and a test fails
//! when the committed copy is stale, so it is the exact published surface.
//! Each `/** … */` block documents the declaration that follows it.

use super::summary;
use crate::workspace::Workspace;

const HEADER: &str = "crates/openbim-ifc-capi/include/openbim_ifc.h";
const PREFIX: &str = "openbim_ifc_v0_1_";
const STATUS: &str = "OPENBIM_IFC_STATUS_";
const CONSTANT: &str = "#define OPENBIM_IFC_";

pub(super) fn reference(workspace: &Workspace) -> Result<String, String> {
    let header = std::fs::read_to_string(workspace.root.join(HEADER))
        .map_err(|error| format!("{HEADER}: {error}"))?;
    let found = declarations(&header);
    if found.functions.is_empty() {
        return Err(format!("{HEADER}: no `{PREFIX}*` function found"));
    }
    if found.types.is_empty() || found.constants.is_empty() {
        return Err(format!("{HEADER}: no documented type or constant found"));
    }

    let mut out = vec!["## Types".to_owned(), String::new()];
    for ty in &found.types {
        out.push(format!("### `{}`", ty.name));
        out.push(String::new());
        if ty.fields.is_empty() {
            out.push(format!("```c\n{}\n```", ty.declaration));
            out.push(String::new());
            out.push(markdown(&ty.doc));
        } else {
            out.push(markdown(&ty.doc));
            out.push(String::new());
            out.push("| Field | Type | Meaning |".to_owned());
            out.push("| --- | --- | --- |".to_owned());
            for (field, kind, doc) in &ty.fields {
                out.push(format!("| `{field}` | `{kind}` | {} |", summary(doc)));
            }
        }
        out.push(String::new());
    }
    out.push("## Constants".to_owned());
    out.push(String::new());
    out.push("| Constant | Value | Meaning |".to_owned());
    out.push("| --- | ---: | --- |".to_owned());
    for (name, value, doc) in &found.constants {
        out.push(format!("| `{name}` | {value} | {} |", summary(doc)));
    }
    out.push(String::new());
    out.push("## Functions".to_owned());
    out.push(String::new());
    for (signature, doc) in &found.functions {
        let name = signature
            .split('(')
            .next()
            .and_then(|head| head.split_whitespace().last())
            .unwrap_or("")
            .trim_start_matches('*');
        out.push(format!("### `{name}`"));
        out.push(String::new());
        out.push(format!("```c\n{signature}\n```"));
        out.push(String::new());
        out.push(markdown(doc));
        out.push(String::new());
    }
    out.push("## Status codes".to_owned());
    out.push(String::new());
    out.push("| Status | Value | Meaning |".to_owned());
    out.push("| --- | ---: | --- |".to_owned());
    for (name, value, doc) in &found.statuses {
        out.push(format!("| `{name}` | {value} | {} |", summary(doc)));
    }
    Ok(out.join("\n").trim_end().to_owned())
}

/// A cbindgen doc comment is the Rust doc comment it came from: turn its
/// rustdoc headings into run-in labels (a `# Safety` line would otherwise
/// become a page title) and its intra-doc links into plain names.
fn markdown(doc: &str) -> String {
    doc.trim()
        .lines()
        .map(|line| match line.trim_start().strip_prefix("# ") {
            Some(heading) => format!("**{heading}.**"),
            None => crate::docs::reference::crate_docs::flatten_links(line),
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// A typedef: an alias (`typedef uint64_t OpenbimIfcModel;`) or a struct
/// with its fields `(name, type, doc)`.
#[derive(Debug, PartialEq)]
struct Type {
    name: String,
    declaration: String,
    doc: String,
    fields: Vec<(String, String, String)>,
}

/// Everything documented in the header, in header order.
#[derive(Debug, Default)]
struct Declarations {
    functions: Vec<(String, String)>,
    statuses: Vec<(String, String, String)>,
    constants: Vec<(String, String, String)>,
    types: Vec<Type>,
}

/// The text of the `/** … */` block that opens on `first`, consuming its
/// remaining lines from `lines`.
fn doc_block<'a>(first: &str, lines: &mut impl Iterator<Item = &'a str>) -> String {
    let mut block = vec![first.trim_start_matches("/**").to_owned()];
    let mut closed = first.ends_with("*/") && first.len() > 3;
    while !closed {
        let Some(next) = lines.next() else { break };
        let next = next.trim();
        closed = next.ends_with("*/");
        block.push(next.to_owned());
    }
    let text: Vec<String> = block
        .iter()
        .map(|l| {
            l.trim_end_matches("*/")
                .trim()
                .trim_start_matches('*')
                .strip_prefix(' ')
                .unwrap_or_else(|| l.trim_end_matches("*/").trim().trim_start_matches('*'))
                .to_owned()
        })
        .collect();
    text.join("\n").trim().to_owned()
}

/// Documented functions (signature, doc), status codes and constants (name,
/// value, doc) and typedefs.
fn declarations(header: &str) -> Declarations {
    let mut found = Declarations::default();
    let mut doc: Option<String> = None;
    let mut lines = header.lines();
    while let Some(line) = lines.next() {
        let trimmed = line.trim();
        if trimmed.starts_with("/**") {
            doc = Some(doc_block(trimmed, &mut lines));
            continue;
        }
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with(STATUS) && trimmed.contains('=') {
            let (name, value) = trimmed.split_once('=').unwrap_or((trimmed, ""));
            found.statuses.push((
                name.trim().to_owned(),
                value.trim().trim_end_matches(',').to_owned(),
                doc.take().unwrap_or_default(),
            ));
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("#define ") {
            let text = doc.take();
            if let (true, Some(text), Some((name, value))) =
                (trimmed.starts_with(CONSTANT), text, rest.split_once(' '))
            {
                found
                    .constants
                    .push((name.to_owned(), value.trim().to_owned(), text));
            }
            continue;
        }
        if trimmed == "typedef struct {" {
            let text = doc.take().unwrap_or_default();
            let mut fields = Vec::new();
            let mut field_doc = String::new();
            while let Some(inner) = lines.next() {
                let inner = inner.trim();
                if inner.starts_with("/**") {
                    field_doc = doc_block(inner, &mut lines);
                } else if let Some(name) = inner.strip_prefix('}') {
                    let name = name.trim().trim_end_matches(';').to_owned();
                    found.types.push(Type {
                        declaration: format!("typedef struct {{ ... }} {name};"),
                        name,
                        doc: text,
                        fields,
                    });
                    break;
                } else if let Some(declaration) = inner.strip_suffix(';') {
                    let split = declaration.rfind([' ', '*']).unwrap_or(0);
                    let (kind, name) = declaration.split_at(split + 1);
                    fields.push((
                        name.trim().to_owned(),
                        kind.trim().to_owned(),
                        std::mem::take(&mut field_doc),
                    ));
                }
            }
            continue;
        }
        if let (Some(alias), Some(text)) = (trimmed.strip_prefix("typedef "), doc.as_ref()) {
            if !alias.starts_with("enum") && !alias.starts_with("struct") {
                let name = alias
                    .trim_end_matches(';')
                    .split_whitespace()
                    .last()
                    .unwrap_or("")
                    .to_owned();
                found.types.push(Type {
                    name,
                    declaration: trimmed.to_owned(),
                    doc: text.clone(),
                    fields: Vec::new(),
                });
                doc = None;
                continue;
            }
        }
        if trimmed.contains(PREFIX) && trimmed.contains('(') {
            let mut statement = trimmed.to_owned();
            while !statement.ends_with(';') {
                let Some(next) = lines.next() else { break };
                statement.push(' ');
                statement.push_str(next.trim());
            }
            let signature = statement.split_whitespace().collect::<Vec<_>>().join(" ");
            found
                .functions
                .push((signature, doc.take().unwrap_or_default()));
            continue;
        }
        doc = None;
    }
    found
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn functions_and_statuses_carry_their_docs() {
        let header = "/**\n * Success.\n */\n  OPENBIM_IFC_STATUS_OK = 0,\n\
                      /**\n * Parse a file.\n *\n * Details.\n */\n\
                      OpenbimIfcStatus openbim_ifc_v0_1_model_parse(const uint8_t *data,\n    size_t len);\n";
        let found = declarations(header);
        assert_eq!(
            found.statuses,
            [(
                "OPENBIM_IFC_STATUS_OK".into(),
                "0".into(),
                "Success.".into()
            )]
        );
        assert_eq!(
            found.functions,
            [(
                "OpenbimIfcStatus openbim_ifc_v0_1_model_parse(const uint8_t *data, size_t len);"
                    .into(),
                "Parse a file.\n\nDetails.".into()
            )]
        );
    }

    #[test]
    fn types_and_constants_carry_their_docs() {
        let header = "#define OPENBIM_IFC_CAPI_V0_1_H\n\
                      /**\n * Base.\n */\n#define OPENBIM_IFC_HANDLE_BASE 42\n\
                      /**\n * A handle.\n */\ntypedef uint64_t OpenbimIfcModel;\n\
                      /**\n * A node.\n */\ntypedef struct {\n  /**\n   * Its kind.\n   */\n  int32_t kind;\n\
                      /**\n   * Its string.\n   */\n  const uint8_t *text;\n} OpenbimIfcNode;\n";
        let found = declarations(header);
        assert_eq!(
            found.constants,
            [(
                "OPENBIM_IFC_HANDLE_BASE".into(),
                "42".into(),
                "Base.".into()
            )]
        );
        assert_eq!(found.types.len(), 2);
        assert_eq!(found.types[0].name, "OpenbimIfcModel");
        assert_eq!(
            found.types[0].declaration,
            "typedef uint64_t OpenbimIfcModel;"
        );
        assert_eq!(
            found.types[1].fields,
            [
                ("kind".into(), "int32_t".into(), "Its kind.".into()),
                (
                    "text".into(),
                    "const uint8_t *".into(),
                    "Its string.".into()
                ),
            ]
        );
    }
}
