//! `crates/openbim-ifc-capi/include/openbim_ifc.h`: every function and status code.
//!
//! The header is generated by cbindgen from the Rust exports and a test fails
//! when the committed copy is stale, so it is the exact published surface.
//! Each `/** … */` block documents the declaration that follows it.

use super::summary;
use crate::workspace::Workspace;

const HEADER: &str = "crates/openbim-ifc-capi/include/openbim_ifc.h";
const PREFIX: &str = "openbim_ifc_v0_1_";
const STATUS: &str = "OPENBIM_IFC_STATUS_";

pub(super) fn reference(workspace: &Workspace) -> Result<String, String> {
    let header = std::fs::read_to_string(workspace.root.join(HEADER))
        .map_err(|error| format!("{HEADER}: {error}"))?;
    let (functions, statuses) = declarations(&header);
    if functions.is_empty() {
        return Err(format!("{HEADER}: no `{PREFIX}*` function found"));
    }

    let mut out = vec!["### Functions".to_owned(), String::new()];
    for (signature, doc) in &functions {
        let name = signature
            .split('(')
            .next()
            .and_then(|head| head.split_whitespace().last())
            .unwrap_or("")
            .trim_start_matches('*');
        out.push(format!("#### `{name}`"));
        out.push(String::new());
        out.push(format!("```c\n{signature}\n```"));
        out.push(String::new());
        out.push(markdown(doc));
        out.push(String::new());
    }
    out.push("### Status codes".to_owned());
    out.push(String::new());
    out.push("| Status | Value | Meaning |".to_owned());
    out.push("| --- | ---: | --- |".to_owned());
    for (name, value, doc) in &statuses {
        out.push(format!("| `{name}` | {value} | {} |", summary(doc)));
    }
    Ok(out.join("\n").trim_end().to_owned())
}

/// A cbindgen doc comment is the Rust doc comment it came from: turn its
/// rustdoc headings into run-in labels (a `# Safety` line would otherwise
/// become a page title) and its intra-doc links into plain names.
fn markdown(doc: &str) -> String {
    doc.trim()
        .lines()
        .map(|line| match line.trim_start().strip_prefix("# ") {
            Some(heading) => format!("**{heading}.**"),
            None => crate::docs::reference::crate_docs::flatten_links(line),
        })
        .collect::<Vec<_>>()
        .join("\n")
}

type Functions = Vec<(String, String)>;
type Statuses = Vec<(String, String, String)>;

/// Documented functions (signature, doc) and status codes (name, value, doc).
fn declarations(header: &str) -> (Functions, Statuses) {
    let mut functions = Vec::new();
    let mut statuses = Vec::new();
    let mut doc: Option<String> = None;
    let mut lines = header.lines().peekable();
    while let Some(line) = lines.next() {
        let trimmed = line.trim();
        if trimmed.starts_with("/**") {
            let mut block = vec![trimmed.trim_start_matches("/**").to_owned()];
            let mut closed = trimmed.ends_with("*/") && trimmed.len() > 3;
            while !closed {
                let Some(next) = lines.next() else { break };
                let next = next.trim();
                closed = next.ends_with("*/");
                block.push(next.to_owned());
            }
            let text: Vec<String> = block
                .iter()
                .map(|l| {
                    l.trim_end_matches("*/")
                        .trim()
                        .trim_start_matches('*')
                        .strip_prefix(' ')
                        .unwrap_or_else(|| l.trim_end_matches("*/").trim().trim_start_matches('*'))
                        .to_owned()
                })
                .collect();
            doc = Some(text.join("\n").trim().to_owned());
            continue;
        }
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with(STATUS) && trimmed.contains('=') {
            let (name, value) = trimmed.split_once('=').unwrap_or((trimmed, ""));
            statuses.push((
                name.trim().to_owned(),
                value.trim().trim_end_matches(',').to_owned(),
                doc.take().unwrap_or_default(),
            ));
            continue;
        }
        if trimmed.contains(PREFIX) && trimmed.contains('(') {
            let mut statement = trimmed.to_owned();
            while !statement.ends_with(';') {
                let Some(next) = lines.next() else { break };
                statement.push(' ');
                statement.push_str(next.trim());
            }
            let signature = statement.split_whitespace().collect::<Vec<_>>().join(" ");
            functions.push((signature, doc.take().unwrap_or_default()));
            continue;
        }
        doc = None;
    }
    (functions, statuses)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn functions_and_statuses_carry_their_docs() {
        let header = "/**\n * Success.\n */\n  OPENBIM_IFC_STATUS_OK = 0,\n\
                      /**\n * Parse a file.\n *\n * Details.\n */\n\
                      OpenbimIfcStatus openbim_ifc_v0_1_model_parse(const uint8_t *data,\n    size_t len);\n";
        let (functions, statuses) = declarations(header);
        assert_eq!(
            statuses,
            [(
                "OPENBIM_IFC_STATUS_OK".into(),
                "0".into(),
                "Success.".into()
            )]
        );
        assert_eq!(
            functions,
            [(
                "OpenbimIfcStatus openbim_ifc_v0_1_model_parse(const uint8_t *data, size_t len);"
                    .into(),
                "Parse a file.\n\nDetails.".into()
            )]
        );
    }
}
