[package]
name = "ifc-style"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
license = "AGPL-3.0-or-later"
authors = ["point-grey"]
repository = "https://github.com/openbimrs/ifc"
description = "Presentation: styles, colours, textures, layers, annotation."

[dependencies]
ifc-schema.workspace = true
ifc-model.workspace = true
