import { readFileSync } from 'node:fs'

import { defineConfig } from 'vitepress'

import { diagramPlugin } from './diagram-plugin.ts'

// Both files are generated by `cargo run -p xtask -- docs` from the ADR files
// and the crate manifests; the gate fails when they are stale. Reading them
// here means a new ADR or crate reaches the sidebar with no edit to this file.
function data(name: string) {
  return JSON.parse(readFileSync(new URL('./data/' + name, import.meta.url), 'utf8'))
}

const adrs: { number: string; slug: string; title: string }[] = data('adrs.json')
const facts: {
  crates: { groups: { key: string; title: string; crates: string[] }[] }
} = data('facts.json')

function adrItems() {
  return adrs.map(function (adr) {
    return { text: adr.number + ' · ' + adr.title, link: '/adr/' + adr.slug }
  })
}

function bindingsSidebar() {
  return [
    {
      text: 'Language bindings',
      items: [
        { text: 'Install', link: '/guide/install' },
        { text: 'JavaScript and TypeScript', link: '/bindings/javascript' },
        { text: 'Python', link: '/bindings/python' },
        { text: 'C and C++', link: '/bindings/c' },
        { text: 'C# and .NET', link: '/bindings/dotnet' },
      ],
    },
    {
      text: 'Cookbooks',
      items: [
        { text: 'JavaScript and TypeScript', link: '/cookbook/javascript' },
        { text: 'Python', link: '/cookbook/python' },
        { text: 'C and C++', link: '/cookbook/c' },
        { text: 'C# and .NET', link: '/cookbook/dotnet' },
        { text: 'Playground', link: '/playground' },
      ],
    },
    { text: 'API references', items: apiItems() },
  ]
}

// The JavaScript and Python references are generated by TypeDoc and pdoc in
// the Pages workflow and copied into dist/api/typedoc/ and dist/api/pdoc/
// after the VitePress build, as rustdoc is (see ignoreDeadLinks below).
function apiItems() {
  return [
    { text: 'Overview', link: '/api/' },
    { text: 'Rust', link: '/api/rust' },
    { text: 'Rust (rustdoc)', link: '/api/rustdoc/ifc/index.html', target: '_self' },
    { text: 'JavaScript (TypeDoc)', link: '/api/typedoc/index.html', target: '_self' },
    { text: 'Python (pdoc)', link: '/api/pdoc/openbim_ifc.html', target: '_self' },
    { text: 'C header', link: '/api/c' },
    { text: 'C# and .NET', link: '/bindings/dotnet#api' },
  ]
}

function referenceSidebar() {
  const groups = facts.crates.groups
    .filter(function (group) {
      return group.crates.length > 0
    })
    .map(function (group) {
      return {
        text: group.title,
        collapsed: group.key !== 'facade',
        items: group.crates.map(function (name) {
          return { text: name, link: '/reference/crates/' + name }
        }),
      }
    })
  return [{ text: 'Crate reference', items: [{ text: 'All crates', link: '/reference/' }] }].concat(groups)
}

export default defineConfig({
  title: 'openbim-ifc',
  description: 'Pure-Rust IFC model, codecs, schema metadata, and typed domain projections.',
  lang: 'en-US',
  base: '/ifc/',
  cleanUrls: true,
  lastUpdated: true,
  // AGENTS.md files are agent context beside the site sources, not
  // pages. Excluding them keeps the dead-link gate meaningful, since their
  // relative pointers target repository files rather than routes.
  srcExclude: ['**/AGENTS.md', 'adr/_template.md'],
  // rustdoc, TypeDoc and pdoc are generated in the Pages workflow and copied
  // into dist/api/{rustdoc,typedoc,pdoc}/ after this build runs, so VitePress
  // cannot see those files here. Scoped to those prefixes: every other dead
  // link still fails the build.
  ignoreDeadLinks: [/^\/api\/(rustdoc|typedoc|pdoc)\//],
  markdown: {
    // The generated capability tables emit status badges as inline
    // `<span class="status-...">` and delimit their regions with HTML
    // comments. With `html: false` markdown-it escapes both, so the badge
    // markup and the `CAPABILITIES:*:BEGIN` markers render as visible text.
    // Content here is generated from crate source by scripts/sync-*.py, not
    // authored by third parties, so inline HTML is safe to enable.
    html: true,
    // No `math`: no page uses it, it needs the optional peer
    // markdown-it-mathjax3 (a lockfile regenerated without it fails the
    // build), and it would read STEP's `$` null markers as TeX delimiters.
    config: diagramPlugin,
  },
  sitemap: { hostname: 'https://openbimrs.github.io/ifc/' },
  head: [
    ['meta', { name: 'theme-color', content: '#1d4ed8' }],
    ['meta', { name: 'robots', content: 'index,follow' }],
  ],
  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'openbim-ifc',
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Install', link: '/guide/install' },
      { text: 'Bindings', link: '/bindings/javascript' },
      { text: 'Cookbook', link: '/cookbook/javascript' },
      { text: 'Playground', link: '/playground' },
      { text: 'Capabilities', link: '/capabilities' },
      { text: 'Coverage', link: '/coverage' },
      { text: 'Use cases', link: '/use-cases/' },
      { text: 'Architecture', link: '/architecture/' },
      { text: 'Reference', link: '/reference/' },
      { text: 'API', link: '/api/' },
      { text: 'Roadmap', link: '/project/roadmap' },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Install', link: '/guide/install' },
            { text: 'Getting started', link: '/guide/getting-started' },
            { text: 'Command line', link: '/guide/cli' },
            { text: 'Construction resources', link: '/guide/resources' },
            { text: 'Approvals and constraints', link: '/guide/approvals-constraints' },
            { text: 'Contributing', link: '/guide/contributing' },
          ],
        },
      ].concat(bindingsSidebar()),
      '/bindings/': bindingsSidebar(),
      '/cookbook/': bindingsSidebar(),
      '/playground': bindingsSidebar(),
      '/use-cases/': [
        {
          text: 'Use cases',
          items: [
            { text: 'Overview', link: '/use-cases/' },
            { text: '2D approval plans', link: '/use-cases/2d-approval-plans' },
            { text: 'Structural analysis', link: '/use-cases/structural-analysis' },
            { text: 'Model checking', link: '/use-cases/model-checking' },
          ],
        },
      ],
      '/architecture/': [
        {
          text: 'Architecture',
          items: [
            { text: 'System design', link: '/architecture/' },
            { text: 'Crate map', link: '/architecture/crates' },
            { text: 'The Axiolid boundary', link: '/architecture/axiolid-boundary' },
          ],
        },
        { text: 'Decision records', items: adrItems() },
      ],
      '/adr/': [
        {
          text: 'Decision records',
          items: [{ text: 'Index', link: '/adr/' }].concat(adrItems()),
        },
      ],
      '/reference/': referenceSidebar(),
      '/api/': [{ text: 'API reference', items: apiItems() }],
      '/project/': [
        {
          text: 'Project',
          items: [
            { text: 'Roadmap', link: '/project/roadmap' },
            { text: 'Changelog', link: '/project/changelog' },
          ],
        },
      ],
      '/': [
        {
          text: 'Start here',
          items: [
            { text: 'Overview', link: '/' },
            { text: 'Getting started', link: '/guide/getting-started' },
            { text: 'Cookbooks', link: '/cookbook/javascript' },
            { text: 'Playground', link: '/playground' },
            { text: 'Capabilities', link: '/capabilities' },
            { text: 'Coverage', link: '/coverage' },
            { text: 'Schema looseness', link: '/schema-looseness' },
            { text: 'Use cases', link: '/use-cases/' },
          ],
        },
        {
          text: 'Architecture',
          items: [
            { text: 'System design', link: '/architecture/' },
            { text: 'Crate map', link: '/architecture/crates' },
            { text: 'The Axiolid boundary', link: '/architecture/axiolid-boundary' },
            { text: 'Crate reference', link: '/reference/' },
          ],
        },
        {
          text: 'Project',
          items: [
            { text: 'Roadmap', link: '/project/roadmap' },
            { text: 'Changelog', link: '/project/changelog' },
            { text: 'Decision records', link: '/adr/' },
            { text: 'Contributing', link: '/guide/contributing' },
          ],
        },
      ],
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/openbimrs/ifc' }],
    editLink: {
      pattern: 'https://github.com/openbimrs/ifc/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },
    search: { provider: 'local' },
    footer: {
      message: 'Released under the AGPL-3.0-or-later licence. ISO and CEN standards material is not redistributed.',
      copyright: 'Copyright (c) 2026 openbimrs contributors',
    },
  },
})
