"""Type stubs for the compiled extension. The public API is openbim_ifc."""

from typing import Any, Dict, Iterable, List, Optional, Tuple

class IfcError(Exception):
    code: str

class NativeModel:
    def __init__(self) -> None: ...
    @staticmethod
    def parse(data: bytes) -> NativeModel: ...
    def write(self) -> bytes: ...
    def __len__(self) -> int: ...
    @property
    def schema(self) -> Optional[str]: ...
    def diagnostics(self) -> List[str]: ...
    def ids(self) -> List[int]: ...
    def ids_of_type(self, type_name: str) -> List[int]: ...
    def ids_of_type_including_subtypes(self, type_name: str) -> List[int]: ...
    def type_of(self, id: int) -> str: ...
    def attributes(self, id: int) -> List[Dict[str, Any]]: ...
    def attribute(self, id: int, index: int) -> Dict[str, Any]: ...
    def set_attribute(self, id: int, index: int, value: Dict[str, Any]) -> Dict[str, Any]: ...
    def add(self, type_name: str, attributes: Iterable[Dict[str, Any]]) -> int: ...
    def remove(self, id: int) -> None: ...
    def dangling_references(self) -> List[Tuple[int, int]]: ...
