/* openbim-ifc C ABI v0.1 -- see openbim-ifc-capi/README.md for the ownership protocol. */

#ifndef OPENBIM_IFC_CAPI_V0_1_H
#define OPENBIM_IFC_CAPI_V0_1_H

#pragma once

/* Generated by cbindgen from openbim-ifc-capi; do not edit. Regenerate with UPDATE_HEADER=1 cargo test -p openbim-ifc-capi --test header. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Binary digits in the string range.
 */
#define OPENBIM_IFC_KIND_BINARY 7

/**
 * `.T.`/`.F.`; `int_value` is 1 or 0.
 */
#define OPENBIM_IFC_KIND_BOOL 2

/**
 * `*`.
 */
#define OPENBIM_IFC_KIND_DERIVED 1

/**
 * Enumeration name in the string range.
 */
#define OPENBIM_IFC_KIND_ENUM 8

/**
 * Integer in `int_value`.
 */
#define OPENBIM_IFC_KIND_INTEGER 4

/**
 * Aggregate; `child_count` children follow.
 */
#define OPENBIM_IFC_KIND_LIST 10

/**
 * Kind codes. Plain integers, not a Rust enum, so an unknown value from C
 * is rejected rather than read as an invalid discriminant.
 */
#define OPENBIM_IFC_KIND_NULL 0

/**
 * Finite real in `real_value`.
 */
#define OPENBIM_IFC_KIND_REAL 5

/**
 * Entity id in `int_value` (non-negative).
 */
#define OPENBIM_IFC_KIND_REF 9

/**
 * Text in the string range.
 */
#define OPENBIM_IFC_KIND_TEXT 6

/**
 * Typed wrapper; type name in the string range, one child follows.
 */
#define OPENBIM_IFC_KIND_TYPED 11

/**
 * `.U.`.
 */
#define OPENBIM_IFC_KIND_UNKNOWN 3

/**
 * Read a real written without its decimal point (`1E-05`) as that real,
 * with a diagnostic.
 */
#define OPENBIM_IFC_PARSE_ACCEPT_REAL_WITHOUT_POINT 4

/**
 * Report duplicate instance ids and references to undefined ids as
 * diagnostics. Nothing is dropped.
 */
#define OPENBIM_IFC_PARSE_CHECK_REFERENCES 2

/**
 * The lenient preset: `SKIP_MALFORMED | ACCEPT_REAL_WITHOUT_POINT`.
 */
#define OPENBIM_IFC_PARSE_LENIENT 5

/**
 * Skip a data record that cannot be parsed and report it as a diagnostic,
 * instead of failing the read.
 */
#define OPENBIM_IFC_PARSE_SKIP_MALFORMED 1

/**
 * Result of every ABI call. `Ok` is zero; every failure is non-zero.
 *
 * The values from `Parse` to `FeatureDisabled`, `InvalidModel`, and
 * `MissingReference` to `DerivedAttribute`, are the binding errors shared
 * with the JavaScript and Python bindings; the rest describe misuse of the
 * C boundary itself.
 */
enum OpenbimIfcStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Success.
   */
  OPENBIM_IFC_STATUS_OK = 0,
  /**
   * A required pointer was null.
   */
  OPENBIM_IFC_STATUS_NULL_POINTER = 1,
  /**
   * An argument was malformed (bad UTF-8, a malformed value tape, ...).
   */
  OPENBIM_IFC_STATUS_INVALID_ARGUMENT = 2,
  /**
   * The model handle is zero, stale, or already destroyed.
   */
  OPENBIM_IFC_STATUS_INVALID_HANDLE = 3,
  /**
   * The output buffer is smaller than `*out_required`.
   */
  OPENBIM_IFC_STATUS_BUFFER_TOO_SMALL = 4,
  /**
   * The STEP input could not be parsed (`parse`).
   */
  OPENBIM_IFC_STATUS_PARSE = 10,
  /**
   * The model could not be serialized (`write`).
   */
  OPENBIM_IFC_STATUS_WRITE = 11,
  /**
   * No entity has the given id (`missing-entity`).
   */
  OPENBIM_IFC_STATUS_MISSING_ENTITY = 12,
  /**
   * A value did not follow the encoding (`invalid-value`).
   */
  OPENBIM_IFC_STATUS_INVALID_VALUE = 13,
  /**
   * An id or index is outside the representable range (`out-of-range`).
   */
  OPENBIM_IFC_STATUS_OUT_OF_RANGE = 14,
  /**
   * The file's schema is not bundled, or a domain view does not read it
   * (`unsupported-schema`).
   */
  OPENBIM_IFC_STATUS_UNSUPPORTED_SCHEMA = 15,
  /**
   * A file could not be opened or read (`io`).
   */
  OPENBIM_IFC_STATUS_IO = 16,
  /**
   * No ifcXML XSD profile has that name (`unsupported-profile`).
   */
  OPENBIM_IFC_STATUS_UNSUPPORTED_PROFILE = 17,
  /**
   * This build leaves out the feature the call needs (`feature-disabled`).
   */
  OPENBIM_IFC_STATUS_FEATURE_DISABLED = 18,
  /**
   * A domain view refused the file's data as malformed, ambiguous or
   * unprovable (`invalid-model`).
   */
  OPENBIM_IFC_STATUS_INVALID_MODEL = 19,
  /**
   * The requested value does not exist (no schema token, no error, ...).
   */
  OPENBIM_IFC_STATUS_NO_VALUE = 20,
  /**
   * A domain view followed a reference to an entity the file lacks
   * (`missing-reference`).
   */
  OPENBIM_IFC_STATUS_MISSING_REFERENCE = 21,
  /**
   * A domain view stopped at a cycle or its depth budget
   * (`budget-exceeded`).
   */
  OPENBIM_IFC_STATUS_BUDGET_EXCEEDED = 22,
  /**
   * A domain view met a construct it does not interpret (`unsupported`).
   */
  OPENBIM_IFC_STATUS_UNSUPPORTED = 23,
  /**
   * A domain query named an entity of a type it does not accept, or a
   * property edit a set type the set does not have (`wrong-entity-type`).
   */
  OPENBIM_IFC_STATUS_WRONG_ENTITY_TYPE = 24,
  /**
   * A property edit wrote a value its PSD/QTO template or property
   * enumeration refuses (`template-violation`).
   */
  OPENBIM_IFC_STATUS_TEMPLATE_VIOLATION = 25,
  /**
   * A property edit removed a property the object does not state
   * (`missing-property`).
   */
  OPENBIM_IFC_STATUS_MISSING_PROPERTY = 26,
  /**
   * A property edit wrote to a `Pset_`/`Qto_` set before its release's
   * catalog was loaded (`catalog-not-loaded`). This library embeds the
   * catalog, so it never returns this; the value is reserved so every
   * binding code has one.
   */
  OPENBIM_IFC_STATUS_CATALOG_NOT_LOADED = 27,
  /**
   * A by-name attribute access named no explicit attribute of the
   * entity's type in the declared release (`unknown-attribute`).
   */
  OPENBIM_IFC_STATUS_UNKNOWN_ATTRIBUTE = 28,
  /**
   * A by-name attribute write named a slot the entity's type derives,
   * written `*` (`derived-attribute`).
   */
  OPENBIM_IFC_STATUS_DERIVED_ATTRIBUTE = 29,
  /**
   * A Rust panic was contained at the boundary. Report it as a bug.
   */
  OPENBIM_IFC_STATUS_PANIC = 255,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum OpenbimIfcStatus OpenbimIfcStatus;
#else
typedef int32_t OpenbimIfcStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Opaque model handle. Zero is never a valid handle.
 */
typedef uint64_t OpenbimIfcModel;

/**
 * One node of a value tape. Fields a kind does not use are zero.
 */
typedef struct {
  /**
   * One of the `OPENBIM_IFC_KIND_*` codes.
   */
  int32_t kind;
  /**
   * Children following a `list` node; 0 otherwise.
   */
  uint32_t child_count;
  /**
   * Payload of `bool` (0/1), `integer` and `ref`.
   */
  int64_t int_value;
  /**
   * Payload of `real`.
   */
  double real_value;
  /**
   * Byte offset of this node's string in the string buffer.
   */
  uint64_t str_offset;
  /**
   * Byte length of this node's string (no NUL terminator).
   */
  uint64_t str_len;
} OpenbimIfcValueNode;

/**
 * Counts from one validation run.
 */
typedef struct {
  /**
   * Number of findings on the tape.
   */
  size_t finding_count;
  /**
   * Schema violations.
   */
  size_t errors;
  /**
   * Implemented rules that could not be decided for an instance.
   */
  size_t evaluation_errors;
  /**
   * Legal but suspicious conditions.
   */
  size_t warnings;
  /**
   * Rules this validator does not evaluate.
   */
  size_t unsupported;
  /**
   * 1 when there are no errors and no evaluation errors, else 0.
   */
  uint32_t conformant;
  /**
   * 1 when the run hit `max_findings`: the counts are lower bounds.
   */
  uint32_t truncated;
} OpenbimIfcValidationSummary;

/**
 * ABI and crate versions, reported separately: the ABI version changes only
 * when the C surface does, the crate version on every release.
 */
typedef struct {
  /**
   * ABI major; also the `v0_1` in every symbol name.
   */
  uint16_t abi_major;
  /**
   * ABI minor.
   */
  uint16_t abi_minor;
  /**
   * ABI patch.
   */
  uint16_t abi_patch;
  /**
   * Crate major.
   */
  uint16_t crate_major;
  /**
   * Crate minor.
   */
  uint16_t crate_minor;
  /**
   * Crate patch.
   */
  uint16_t crate_patch;
} OpenbimIfcVersion;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Append an entity of `type_name` whose `attribute_count` attributes are
 * on the tape back to back, and write its new id to `out_id`.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_entity_set_attribute`]; `type_name` valid for
 * `type_len` reads; `out_id` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_add(OpenbimIfcModel model,
                                             const uint8_t *type_name,
                                             size_t type_len,
                                             size_t attribute_count,
                                             const OpenbimIfcValueNode *nodes,
                                             size_t node_count,
                                             const uint8_t *strings,
                                             size_t string_len,
                                             uint64_t *out_id);

/**
 * Attribute `index` of entity `id` as a value tape (`$` past the end).
 *
 * # Safety
 * As for `fill_tape`: each buffer null with capacity 0, or valid for its
 * capacity; both `out_*_required` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_attribute(OpenbimIfcModel model,
                                                   uint64_t id,
                                                   size_t index,
                                                   OpenbimIfcValueNode *nodes,
                                                   size_t node_capacity,
                                                   size_t *out_nodes_required,
                                                   uint8_t *strings,
                                                   size_t string_capacity,
                                                   size_t *out_strings_required);

/**
 * Attribute `name` (UTF-8, `name_len` bytes, any case, e.g. `Name`) of
 * entity `id` as a value tape; `NULL` when the record stops before its
 * slot.
 *
 * `MissingEntity`, `UnknownAttribute`, `UnsupportedSchema` as for
 * [`openbim_ifc_v0_1_entity_attribute_names`].
 *
 * # Safety
 * `name` valid for `name_len` reads; otherwise as for
 * `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_attribute_by_name(OpenbimIfcModel model,
                                                           uint64_t id,
                                                           const uint8_t *name,
                                                           size_t name_len,
                                                           OpenbimIfcValueNode *nodes,
                                                           size_t node_capacity,
                                                           size_t *out_nodes_required,
                                                           uint8_t *strings,
                                                           size_t string_capacity,
                                                           size_t *out_strings_required);

/**
 * Every explicit attribute of entity `id` in slot order, inherited first:
 * a `LIST` of `AttributeInfo` records, their number in `out_count`.
 * `AttributeInfo`: name (`TEXT`, the schema's spelling), index
 * (`INTEGER`, the slot), type name (`TEXT`), optional (`BOOL`), aggregate
 * (`BOOL`), derived (`BOOL`: written `*`, not writable), declared by
 * (`TEXT`, the entity introducing it). `INVERSE` attributes hold no slot
 * and are not listed.
 *
 * `MissingEntity`; `UnsupportedSchema` when the header names no bundled
 * release or the release does not declare the entity's type.
 *
 * # Safety
 * `out_count` valid for one write; otherwise as for
 * `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_attribute_names(OpenbimIfcModel model,
                                                         uint64_t id,
                                                         size_t *out_count,
                                                         OpenbimIfcValueNode *nodes,
                                                         size_t node_capacity,
                                                         size_t *out_nodes_required,
                                                         uint8_t *strings,
                                                         size_t string_capacity,
                                                         size_t *out_strings_required);

/**
 * Every attribute of entity `id`, back to back on one tape, plus how many
 * top-level values it holds.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_entity_attribute`]; `out_count` valid for one
 * write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_attributes(OpenbimIfcModel model,
                                                    uint64_t id,
                                                    size_t *out_count,
                                                    OpenbimIfcValueNode *nodes,
                                                    size_t node_capacity,
                                                    size_t *out_nodes_required,
                                                    uint8_t *strings,
                                                    size_t string_capacity,
                                                    size_t *out_strings_required);

/**
 * Remove entity `id`; references to it are left dangling.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_remove(OpenbimIfcModel model, uint64_t id);

/**
 * Set attribute `index` of entity `id` from a one-value tape. Writing past
 * the end pads the gap with `$`.
 *
 * # Safety
 * `nodes` must be valid for `node_count` reads and `strings` for
 * `string_len` reads (either may be null when its length is 0).
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_set_attribute(OpenbimIfcModel model,
                                                       uint64_t id,
                                                       size_t index,
                                                       const OpenbimIfcValueNode *nodes,
                                                       size_t node_count,
                                                       const uint8_t *strings,
                                                       size_t string_len);

/**
 * Set attribute `name` (UTF-8, any case) of entity `id` from a one-value
 * tape. Every check runs before the write, so a refusal changes nothing.
 *
 * `DerivedAttribute` for a slot the entity's type derives (written `*`);
 * otherwise as for [`openbim_ifc_v0_1_entity_attribute_by_name`] and
 * `openbim_ifc_v0_1_entity_set_attribute`.
 *
 * # Safety
 * `name` valid for `name_len` reads; the tape as for
 * `openbim_ifc_v0_1_entity_set_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_set_attribute_by_name(OpenbimIfcModel model,
                                                               uint64_t id,
                                                               const uint8_t *name,
                                                               size_t name_len,
                                                               const OpenbimIfcValueNode *nodes,
                                                               size_t node_count,
                                                               const uint8_t *strings,
                                                               size_t string_len);

/**
 * The type name of entity `id`, upper-case, NUL-terminated.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_write`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_entity_type(OpenbimIfcModel model,
                                              uint64_t id,
                                              uint8_t *buffer,
                                              size_t capacity,
                                              size_t *out_required);

/**
 * The last error on `model` as its stable code (`parse`, `missing-entity`,
 * ...), NUL-terminated; `NoValue` if the last call succeeded.
 *
 * # Safety
 * `buffer` must be null (with `capacity` 0) or valid for `capacity`
 * writes; `out_required` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_last_error_code(OpenbimIfcModel model,
                                                  uint8_t *buffer,
                                                  size_t capacity,
                                                  size_t *out_required);

/**
 * The last error on `model` as a human message, NUL-terminated; `NoValue`
 * if the last call succeeded.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_last_error_code`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_last_error_message(OpenbimIfcModel model,
                                                     uint8_t *buffer,
                                                     size_t capacity,
                                                     size_t *out_required);

/**
 * Number of live models, for leak checks.
 *
 * # Safety
 * `out_count` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_live_models(size_t *out_count);

/**
 * The classifications of `object`: a `LIST` of `Classification` records,
 * its own then its type object's; `out_count` gets their number.
 * `Classification`: relationship (`REF`), global id, source, type object,
 * target (`REF`), kind (`reference`, `system` or `notation`),
 * identification, name, location, notation (`LIST` of `TEXT`), parents
 * (`LIST` of `REF`), system (`[id, name, source, edition]` or `NULL`).
 *
 * `MissingEntity`, `UnsupportedSchema`, `InvalidModel`,
 * `MissingReference`, `BudgetExceeded`, `FeatureDisabled`.
 *
 * # Safety
 * As for `openbim_ifc_v0_1_model_property_sets`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_classifications(OpenbimIfcModel model,
                                                        uint64_t object,
                                                        size_t *out_count,
                                                        OpenbimIfcValueNode *nodes,
                                                        size_t node_capacity,
                                                        size_t *out_nodes_required,
                                                        uint8_t *strings,
                                                        size_t string_capacity,
                                                        size_t *out_strings_required);

/**
 * Every cost schedule and cost item as one `Cost` record: schedules
 * (`LIST` of `CostSchedule`), items (`LIST` of `CostItem`, each with its
 * `CostValue` tree, applied values tagged), anomalies.
 *
 * `UnsupportedSchema`, `MissingReference`, `BudgetExceeded`,
 * `FeatureDisabled`.
 *
 * # Safety
 * As for `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_cost(OpenbimIfcModel model,
                                             OpenbimIfcValueNode *nodes,
                                             size_t node_capacity,
                                             size_t *out_nodes_required,
                                             uint8_t *strings,
                                             size_t string_capacity,
                                             size_t *out_strings_required);

/**
 * Create an empty model and write its handle to `out_model`.
 *
 * # Safety
 * `out_model` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_create(OpenbimIfcModel *out_model);

/**
 * Every dangling reference as `(from, to)` pairs, flattened: element
 * `2k` is a referencing id, `2k+1` the missing id it points to.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_ids`]; sizes count `u64`s, not pairs.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_dangling_references(OpenbimIfcModel model,
                                                            uint64_t *buffer,
                                                            size_t capacity,
                                                            size_t *out_required);

/**
 * Destroy a model. A stale or repeated handle is `InvalidHandle`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_destroy(OpenbimIfcModel model);

/**
 * Diagnostic `index` as a NUL-terminated string; `OutOfRange` past the end.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_write`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_diagnostic(OpenbimIfcModel model,
                                                   size_t index,
                                                   uint8_t *buffer,
                                                   size_t capacity,
                                                   size_t *out_required);

/**
 * Number of non-fatal parse diagnostics.
 *
 * # Safety
 * `out_count` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_diagnostic_count(OpenbimIfcModel model, size_t *out_count);

/**
 * Every coordinate operation, resolved: a `LIST` of `MapConversion`
 * records, empty when the model has none; `out_count` gets their number.
 * `MapConversion`: operation, kind, source, source kind, target CRS
 * (`ProjectedCrs` record), eastings, northings, orthogonal height, x axis
 * (two `REAL`s), scale, factors (three `REAL`s or `NULL`), project unit
 * and map unit (`[name, metres per unit]`), map unit declared (`BOOL`),
 * linear (three columns of three `REAL`s), translation (three `REAL`s).
 *
 * `UnsupportedSchema` (anything but IFC4 and IFC4X3), `Unsupported`,
 * `InvalidModel`, `MissingReference`, `FeatureDisabled`.
 *
 * # Safety
 * As for `openbim_ifc_v0_1_model_property_sets`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_georeferencing(OpenbimIfcModel model,
                                                       size_t *out_count,
                                                       OpenbimIfcValueNode *nodes,
                                                       size_t node_capacity,
                                                       size_t *out_nodes_required,
                                                       uint8_t *strings,
                                                       size_t string_capacity,
                                                       size_t *out_strings_required);

/**
 * The file header as a value tape: one `LIST` of ten values, in STEP
 * header order -- description (`LIST` of `TEXT`), implementation level,
 * name, time stamp, author (`LIST`), organization (`LIST`), preprocessor
 * version, originating system, authorization, schema (`LIST`).
 *
 * # Safety
 * As for `openbim_ifc_v0_1_entity_attribute`: each buffer null with
 * capacity 0, or valid for its capacity; both `out_*_required` valid for
 * one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_header(OpenbimIfcModel model,
                                               OpenbimIfcValueNode *nodes,
                                               size_t node_capacity,
                                               size_t *out_nodes_required,
                                               uint8_t *strings,
                                               size_t string_capacity,
                                               size_t *out_strings_required);

/**
 * Every entity id, in file order.
 *
 * # Safety
 * `buffer` must be null (with `capacity` 0) or valid for `capacity` `u64`
 * writes; `out_required` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_ids(OpenbimIfcModel model,
                                            uint64_t *buffer,
                                            size_t capacity,
                                            size_t *out_required);

/**
 * Ids of every entity of exactly `type_name` (UTF-8, `type_len` bytes,
 * case-insensitive). Subtypes are not included.
 *
 * # Safety
 * `type_name` must be valid for `type_len` reads; otherwise as for
 * [`openbim_ifc_v0_1_model_ids`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_ids_of_type(OpenbimIfcModel model,
                                                    const uint8_t *type_name,
                                                    size_t type_len,
                                                    uint64_t *buffer,
                                                    size_t capacity,
                                                    size_t *out_required);

/**
 * Ids of every entity of `type_name` or any of its subtypes, using the
 * schema the file's header declares. `UnsupportedSchema` if none is bundled.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_ids_of_type`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_ids_of_type_including_subtypes(OpenbimIfcModel model,
                                                                       const uint8_t *type_name,
                                                                       size_t type_len,
                                                                       uint64_t *buffer,
                                                                       size_t capacity,
                                                                       size_t *out_required);

/**
 * Number of entities.
 *
 * # Safety
 * `out_count` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_len(OpenbimIfcModel model, size_t *out_count);

/**
 * The material association of `object`, its own or its type object's, as
 * one `MaterialAssignment` record, or a `NULL` tape when there is none:
 * relationship, global id, source, type object, target, type name, kind,
 * set, name, materials, layers, profiles, constituents (each a `LIST` of
 * records), usage (record or `NULL`).
 *
 * `MissingEntity`, `UnsupportedSchema`, `InvalidModel`,
 * `MissingReference`, `FeatureDisabled`.
 *
 * # Safety
 * As for `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_material(OpenbimIfcModel model,
                                                 uint64_t object,
                                                 OpenbimIfcValueNode *nodes,
                                                 size_t node_capacity,
                                                 size_t *out_nodes_required,
                                                 uint8_t *strings,
                                                 size_t string_capacity,
                                                 size_t *out_strings_required);

/**
 * Read the STEP file at `path` (UTF-8, `path_len` bytes, no NUL needed)
 * into a model that owns its bytes, and write the new model's handle.
 *
 * Errors as `openbim_ifc_v0_1_model_parse`, plus `Io` when the file cannot
 * be opened or read.
 *
 * # Safety
 * `path` must be valid for `path_len` reads; `out_model` for one write;
 * `error_buffer`, if non-null, for `capacity` writes.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_open(const uint8_t *path,
                                             size_t path_len,
                                             OpenbimIfcModel *out_model,
                                             uint8_t *error_buffer,
                                             size_t capacity);

/**
 * Read the STEP file at `path` through a memory mapping, and write the new
 * model's handle. No copy of the file is made, and its pages belong to the
 * page cache rather than the process heap.
 *
 * # Safety
 * As `openbim_ifc_v0_1_model_open`, and additionally: the file must not
 * be modified or truncated until the model is destroyed. The model decodes
 * entities from the mapping on access; a changed file makes that fail
 * (reported as `Panic`), end the process (`SIGBUS` on truncation), or read
 * other content.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_open_mapped(const uint8_t *path,
                                                    size_t path_len,
                                                    OpenbimIfcModel *out_model,
                                                    uint8_t *error_buffer,
                                                    size_t capacity);

/**
 * As `openbim_ifc_v0_1_model_open_mapped`, under the
 * `OPENBIM_IFC_PARSE_*` `flags`.
 *
 * # Safety
 * As `openbim_ifc_v0_1_model_open_mapped`: the file must not be modified
 * or truncated until the model is destroyed.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_open_mapped_with_options(const uint8_t *path,
                                                                 size_t path_len,
                                                                 uint32_t flags,
                                                                 OpenbimIfcModel *out_model,
                                                                 uint8_t *error_buffer,
                                                                 size_t capacity);

/**
 * As `openbim_ifc_v0_1_model_open`, under the `OPENBIM_IFC_PARSE_*`
 * `flags`.
 *
 * # Safety
 * As `openbim_ifc_v0_1_model_open`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_open_with_options(const uint8_t *path,
                                                          size_t path_len,
                                                          uint32_t flags,
                                                          OpenbimIfcModel *out_model,
                                                          uint8_t *error_buffer,
                                                          size_t capacity);

/**
 * Parse `len` bytes of STEP and write the new model's handle.
 *
 * A parse failure has no model to hold its error, so the message is written
 * to the optional `error_buffer` (NUL-terminated, truncated to `capacity`).
 *
 * # Safety
 * `data` must be valid for `len` reads; `out_model` for one write;
 * `error_buffer`, if non-null, for `capacity` writes.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_parse(const uint8_t *data,
                                              size_t len,
                                              OpenbimIfcModel *out_model,
                                              uint8_t *error_buffer,
                                              size_t capacity);

/**
 * Parse `len` bytes of ifcXML and write the new model's handle.
 *
 * `profile` (UTF-8, `profile_len` bytes) is null with length 0 for the
 * native layout, else `IFC4` or `IFC4X3_ADD2` (any case) for that
 * release's XSD configuration. `UnsupportedProfile` for any other name,
 * `UnsupportedSchema` when the release is not bundled, `Parse` when the
 * document does not read, `FeatureDisabled` without the `ifcxml` feature.
 * The message goes to the optional `error_buffer` as for
 * `openbim_ifc_v0_1_model_parse`.
 *
 * # Safety
 * As `openbim_ifc_v0_1_model_parse`; `profile`, if non-null, valid for
 * `profile_len` reads.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_parse_ifcxml(const uint8_t *data,
                                                     size_t len,
                                                     const uint8_t *profile,
                                                     size_t profile_len,
                                                     OpenbimIfcModel *out_model,
                                                     uint8_t *error_buffer,
                                                     size_t capacity);

/**
 * As `openbim_ifc_v0_1_model_parse`, under the `OPENBIM_IFC_PARSE_*`
 * `flags` (0 is the strict read). What a lenient read recovers from is
 * listed by `openbim_ifc_v0_1_model_diagnostic`.
 *
 * # Safety
 * As `openbim_ifc_v0_1_model_parse`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_parse_with_options(const uint8_t *data,
                                                           size_t len,
                                                           uint32_t flags,
                                                           OpenbimIfcModel *out_model,
                                                           uint8_t *error_buffer,
                                                           size_t capacity);

/**
 * The property sets of `object`: a `LIST` of `PropertySet` records, its
 * own sets first, then those its type object holds; `out_count` gets their
 * number. `PropertySet`: id (`REF`), global id, name, type name, source
 * (`occurrence` or `type`), source id (`REF` or `NULL`), properties
 * (`LIST` of `Property`). `Property`: id, name, type name, kind, value
 * type, unit (`REF` or `NULL`), value (tagged, typed), enumeration,
 * bounds, table, usage, discrimination, quality, members (`LIST` of
 * `Property`).
 *
 * `MissingEntity`, `WrongEntityType`, `UnsupportedSchema` (a release other
 * than IFC2X3, IFC4 or IFC4X3), `InvalidModel`, `FeatureDisabled`.
 *
 * # Safety
 * `out_count` valid for one write; otherwise as for
 * `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_property_sets(OpenbimIfcModel model,
                                                      uint64_t object,
                                                      size_t *out_count,
                                                      OpenbimIfcValueNode *nodes,
                                                      size_t node_capacity,
                                                      size_t *out_nodes_required,
                                                      uint8_t *strings,
                                                      size_t string_capacity,
                                                      size_t *out_strings_required);

/**
 * Remove one property from `object`'s own set:
 * [`openbim_ifc_v0_1_model_set_properties`] with one `REMOVE` edit.
 *
 * # Safety
 * `set` and `name` valid for their lengths (null only for 0).
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_remove_property(OpenbimIfcModel model,
                                                        uint64_t object,
                                                        const uint8_t *set,
                                                        size_t set_len,
                                                        const uint8_t *name,
                                                        size_t name_len);

/**
 * The effective unit of a `measure_type` value (`IFCAREAMEASURE`, UTF-8,
 * `measure_len` bytes): `unit` when non-zero (a property's stated unit),
 * otherwise the project default. The tape is one `ResolvedUnit`: unit
 * (`REF` or `NULL`), from project (`BOOL`), dimensions (`LIST` of seven
 * `INTEGER`s, SI exponents L M T I Θ N J), scale (`REAL`), offset (`REAL`).
 *
 * `InvalidValue` for a type that is no measure, `Unsupported`,
 * `InvalidModel`, `FeatureDisabled`.
 *
 * # Safety
 * `measure_type` valid for `measure_len` reads; otherwise as for
 * `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_resolve_unit(OpenbimIfcModel model,
                                                     const uint8_t *measure_type,
                                                     size_t measure_len,
                                                     uint64_t unit,
                                                     OpenbimIfcValueNode *nodes,
                                                     size_t node_capacity,
                                                     size_t *out_nodes_required,
                                                     uint8_t *strings,
                                                     size_t string_capacity,
                                                     size_t *out_strings_required);

/**
 * The first `FILE_SCHEMA` token as a NUL-terminated string, or `NoValue`.
 *
 * # Safety
 * As for [`openbim_ifc_v0_1_model_write`].
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_schema(OpenbimIfcModel model,
                                               uint8_t *buffer,
                                               size_t capacity,
                                               size_t *out_required);

/**
 * Replace the file header with the one on the tape. A tape of any other
 * shape is `InvalidValue` and leaves the header unchanged.
 *
 * # Safety
 * As for `openbim_ifc_v0_1_entity_set_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_set_header(OpenbimIfcModel model,
                                                   const OpenbimIfcValueNode *nodes,
                                                   size_t node_count,
                                                   const uint8_t *strings,
                                                   size_t string_len);

/**
 * Apply the edits on the tape as one checked transaction: all of them, in
 * order, or none, and the model unchanged.
 *
 * `out_count` gets the number of edits. `out_properties` gets, per edit,
 * the id of the entity holding the property afterwards, or 0 when the
 * batch leaves none; with `properties_capacity` below the edit count the
 * call returns `BufferTooSmall` and applies nothing.
 *
 * `InvalidArgument` or `InvalidValue` for a malformed tape;
 * `MissingEntity`, `WrongEntityType`, `UnsupportedSchema`, `InvalidValue`,
 * `TemplateViolation`, `MissingProperty`, `Unsupported`, `InvalidModel`,
 * `FeatureDisabled` as the shared codes say.
 *
 * # Safety
 * `nodes` valid for `node_count` reads and `strings` for `string_len`
 * (either null when its length is 0); `out_properties` null with capacity
 * 0, or valid for `properties_capacity` writes; `out_count` valid for one
 * write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_set_properties(OpenbimIfcModel model,
                                                       const OpenbimIfcValueNode *nodes,
                                                       size_t node_count,
                                                       const uint8_t *strings,
                                                       size_t string_len,
                                                       uint64_t *out_properties,
                                                       size_t properties_capacity,
                                                       size_t *out_count);

/**
 * Write one value: [`openbim_ifc_v0_1_model_set_properties`] with one
 * `SET` edit. `set` and `name` are UTF-8; the value is a one-value tape;
 * `set_type` (`IfcPropertySet` or `IfcElementQuantity`) may be null with
 * length 0. `out_id` gets the entity holding the property.
 *
 * # Safety
 * `set`, `name` and `set_type` valid for their lengths (null only for 0);
 * the tape as for `openbim_ifc_v0_1_entity_set_attribute`; `out_id` valid
 * for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_set_property(OpenbimIfcModel model,
                                                     uint64_t object,
                                                     const uint8_t *set,
                                                     size_t set_len,
                                                     const uint8_t *name,
                                                     size_t name_len,
                                                     const OpenbimIfcValueNode *nodes,
                                                     size_t node_count,
                                                     const uint8_t *strings,
                                                     size_t string_len,
                                                     const uint8_t *set_type,
                                                     size_t set_type_len,
                                                     uint64_t *out_id);

/**
 * The spatial containment tree as one `SpatialTree` record: release
 * (`TEXT` or `NULL`), roots (`LIST` of `REF`), nodes (`LIST` of
 * `SpatialNode`: id, global id, name, type name, kind, parent, children,
 * elements, referenced), orphans, dangling (`LIST` of `[relation,
 * target]`), anomalies (`LIST` of `[kind, relation, subject, kept]`).
 *
 * `UnsupportedSchema` when the header names no bundled release;
 * `FeatureDisabled`.
 *
 * # Safety
 * As for `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_spatial_tree(OpenbimIfcModel model,
                                                     OpenbimIfcValueNode *nodes,
                                                     size_t node_capacity,
                                                     size_t *out_nodes_required,
                                                     uint8_t *strings,
                                                     size_t string_capacity,
                                                     size_t *out_strings_required);

/**
 * Every system as one `Systems` record: systems (`LIST` of `System`: id,
 * global id, type name, name, long name, predefined type, members,
 * serviced buildings, serviced facilities) and anomalies (`LIST` of
 * `[kind, subject, other, message]`).
 *
 * `UnsupportedSchema`, `FeatureDisabled`.
 *
 * # Safety
 * As for `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_systems(OpenbimIfcModel model,
                                                OpenbimIfcValueNode *nodes,
                                                size_t node_capacity,
                                                size_t *out_nodes_required,
                                                uint8_t *strings,
                                                size_t string_capacity,
                                                size_t *out_strings_required);

/**
 * Products no viewer will draw, in id order, and how many.
 *
 * The tape is a `LIST` of products; each is a `LIST` of four values: the
 * product (`REF`), the reason (`TEXT`: `not-contained-in-spatial-structure`,
 * `no-representation-in-model-context` or `representation-without-context`),
 * the target views its geometry was found in instead (`LIST` of `TEXT`,
 * empty unless the reason is the second), and a one-line message (`TEXT`).
 * `FeatureDisabled` in a build without the `unreachable` feature.
 *
 * # Safety
 * `out_count` valid for one write; otherwise as for
 * `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_unreachable_products(OpenbimIfcModel model,
                                                             size_t *out_count,
                                                             OpenbimIfcValueNode *nodes,
                                                             size_t node_capacity,
                                                             size_t *out_nodes_required,
                                                             uint8_t *strings,
                                                             size_t string_capacity,
                                                             size_t *out_strings_required);

/**
 * Validate against the schema the header declares.
 *
 * `out_summary` gets the counts, also when the tape does not fit. The tape
 * is a `LIST` of findings, sorted by severity, rule, entity and slot; each
 * finding is a `LIST` of seven values: severity (`TEXT`: `error`,
 * `evaluation-error`, `warning` or `unsupported`), rule id (`TEXT`),
 * entity (`REF`, or `NULL` for the file), attribute index (`INTEGER` or
 * `NULL`), attribute name (`TEXT` or `NULL`), path (`TEXT`) and message
 * (`TEXT`). `max_findings` 0 is the validator's default budget (10,000).
 * `UnsupportedSchema` when the declared schema is not bundled;
 * `FeatureDisabled` in a build without the `validate` feature.
 *
 * # Safety
 * `out_summary` valid for one write; otherwise as for
 * `openbim_ifc_v0_1_entity_attribute`.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_validate(OpenbimIfcModel model,
                                                 size_t max_findings,
                                                 OpenbimIfcValidationSummary *out_summary,
                                                 OpenbimIfcValueNode *nodes,
                                                 size_t node_capacity,
                                                 size_t *out_nodes_required,
                                                 uint8_t *strings,
                                                 size_t string_capacity,
                                                 size_t *out_strings_required);

/**
 * Serialize as STEP into a caller buffer; `out_required` gets the size.
 *
 * # Safety
 * `buffer` must be null (with `capacity` 0) or valid for `capacity`
 * writes; `out_required` valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_write(OpenbimIfcModel model,
                                              uint8_t *buffer,
                                              size_t capacity,
                                              size_t *out_required);

/**
 * Serialize as ifcXML into a caller buffer; `out_required` gets the size.
 * `profile` as for `openbim_ifc_v0_1_model_parse_ifcxml`. An XSD-layout
 * write needs the header to declare the profile's schema, and refuses
 * with `Write` what the configuration cannot carry.
 *
 * # Safety
 * As `openbim_ifc_v0_1_model_write`; `profile`, if non-null, valid for
 * `profile_len` reads.
 */
OpenbimIfcStatus openbim_ifc_v0_1_model_write_ifcxml(OpenbimIfcModel model,
                                                     const uint8_t *profile,
                                                     size_t profile_len,
                                                     uint8_t *buffer,
                                                     size_t capacity,
                                                     size_t *out_required);

/**
 * Write the ABI and crate versions.
 *
 * # Safety
 * `out_version` must be null or valid for one write.
 */
OpenbimIfcStatus openbim_ifc_v0_1_version(OpenbimIfcVersion *out_version);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPENBIM_IFC_CAPI_V0_1_H */
