//! Concrete geometry items the schema declares and no source file names.
//!
//! The lowering tables enumerate what the code dispatches, so every row there
//! is Implemented or Refused by construction -- a matrix that can never say
//! "Missing" is a promise, not a measurement. This walks the other way: from
//! the IFC4 schema down, listing concrete `IfcRepresentationItem` subtypes that
//! appear nowhere in the source.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use crate::text::is_word;
use crate::workspace::Workspace;

pub(super) fn table(workspace: &Workspace) -> Result<String, String> {
    // Fail loudly rather than freezing the previous list: a silently stale
    // gap section is exactly the false assurance it exists to prevent.
    let spec = workspace.spec("ifc4-add2-tc1/IFC4.exp").ok_or(
        "references/ifc-spec is missing; run scripts/fetch-ifc-schemas.sh before \
         regenerating docs/capabilities.md",
    )?;
    let bytes = std::fs::read(&spec).map_err(|error| format!("{}: {error}", spec.display()))?;
    let schema = String::from_utf8_lossy(&bytes);
    let mut seen = BTreeSet::new();
    mentioned(&workspace.root, &mut seen);
    let items: Vec<String> = concrete_items(&schema)
        .into_iter()
        .filter(|entity| !seen.contains(&entity.to_lowercase()))
        .collect();

    if items.is_empty() {
        // The missing-schema case already failed above, so an empty list is a
        // measurement, not an absence of one.
        return Ok(
            "Every concrete `IfcRepresentationItem` subtype in IFC4 ADD2 TC1 is \
                   named somewhere in this repository -- implemented, refused, or \
                   explicitly classified as carrying no shape. This section is \
                   generated by walking down from the schema, so it reports zero only \
                   when the walk actually finds nothing unaddressed. Being *named* is \
                   not the same as being implemented: see the tables above for the \
                   status of each one."
                .to_owned(),
        );
    }
    let mut lines = vec![
        format!(
            "{} concrete `IfcRepresentationItem` subtypes in IFC4 ADD2 TC1 appear nowhere \
             in this repository -- not implemented, not refused, not mentioned. They are \
             listed here because the tables above are derived from the code and therefore \
             cannot report an entity the code has never heard of.",
            items.len()
        ),
        String::new(),
        "| Entity | Status |".to_owned(),
        "|---|---|".to_owned(),
    ];
    for item in items {
        lines.push(format!(
            "| `{item}` | <span class=\"status-partial\">Not addressed</span> |"
        ));
    }
    Ok(lines.join("\n"))
}

/// Concrete subtypes of `IfcRepresentationItem`, in schema spelling, sorted
/// by lower-case name.
fn concrete_items(schema: &str) -> Vec<String> {
    let entities = entities(schema);
    let parent: BTreeMap<&String, String> = entities
        .iter()
        .filter_map(|(name, (_, body))| supertype(body).map(|p| (name, p.to_lowercase())))
        .collect();
    let mut family: BTreeSet<String> = BTreeSet::from(["ifcrepresentationitem".to_owned()]);
    loop {
        let before = family.len();
        for (child, parent) in &parent {
            if family.contains(parent) {
                family.insert((*child).clone());
            }
        }
        if family.len() == before {
            break;
        }
    }
    family
        .into_iter()
        .filter_map(|name| {
            let (declared, body) = entities.get(&name)?;
            (!abstract_supertype(body)).then(|| declared.clone())
        })
        .collect()
}

/// `ENTITY name ... END_ENTITY` blocks: lower-case name → (spelling, body).
fn entities(schema: &str) -> BTreeMap<String, (String, String)> {
    let upper = schema.to_ascii_uppercase();
    let mut out = BTreeMap::new();
    let mut offset = 0;
    while let Some(found) = upper[offset..].find("ENTITY") {
        let start = offset + found;
        offset = start + "ENTITY".len();
        let after = &schema[offset..];
        let gap = after.len() - after.trim_start().len();
        if gap == 0 {
            continue;
        }
        let name_start = offset + gap;
        let name_len = schema[name_start..]
            .find(|c: char| !is_word(c))
            .unwrap_or(schema.len() - name_start);
        if name_len == 0 {
            continue;
        }
        let name = &schema[name_start..name_start + name_len];
        let body_start = name_start + name_len;
        let Some(end) = upper[body_start..].find("END_ENTITY") else {
            break;
        };
        let body = &schema[body_start..body_start + end];
        out.insert(name.to_lowercase(), (name.to_owned(), body.to_owned()));
        offset = body_start + end + "END_ENTITY".len();
    }
    out
}

/// The first `SUBTYPE OF (name` in an entity body.
fn supertype(body: &str) -> Option<String> {
    let upper = body.to_ascii_uppercase();
    let mut offset = 0;
    while let Some(found) = upper[offset..].find("SUBTYPE") {
        let at = offset + found + "SUBTYPE".len();
        offset = at;
        let rest = &body[at..];
        let trimmed = rest.trim_start();
        if trimmed.len() == rest.len() {
            continue;
        }
        let Some(rest) = trimmed
            .get(..2)
            .filter(|of| of.eq_ignore_ascii_case("OF"))
            .map(|_| trimmed[2..].trim_start())
        else {
            continue;
        };
        let Some(rest) = rest.strip_prefix('(') else {
            continue;
        };
        let rest = rest.trim_start();
        let length = rest.find(|c: char| !is_word(c)).unwrap_or(rest.len());
        if length > 0 {
            return Some(rest[..length].to_owned());
        }
    }
    None
}

fn abstract_supertype(body: &str) -> bool {
    let upper = body.to_ascii_uppercase();
    let mut offset = 0;
    while let Some(found) = upper[offset..].find("ABSTRACT") {
        let at = offset + found + "ABSTRACT".len();
        offset = at;
        let rest = &upper[at..];
        let trimmed = rest.trim_start();
        if trimmed.len() < rest.len() && trimmed.starts_with("SUPERTYPE") {
            return true;
        }
    }
    false
}

/// Every `Ifc…` identifier (lower-cased) in any `.rs` file under `dir`,
/// skipping build output and hidden directories such as other worktrees.
fn mentioned(dir: &Path, seen: &mut BTreeSet<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        let Ok(kind) = entry.file_type() else {
            continue;
        };
        if kind.is_dir() {
            if name != "target" && !name.starts_with('.') && name != "node_modules" {
                mentioned(&path, seen);
            }
        } else if kind.is_file() && path.extension().is_some_and(|e| e == "rs") {
            let Ok(bytes) = std::fs::read(&path) else {
                continue;
            };
            let text = String::from_utf8_lossy(&bytes);
            let mut rest: &str = &text;
            while let Some(start) = rest.find("Ifc") {
                let after = &rest[start + 3..];
                let length = after
                    .find(|c: char| !c.is_ascii_alphanumeric())
                    .unwrap_or(after.len());
                if length > 0 {
                    seen.insert(format!("ifc{}", after[..length].to_lowercase()));
                }
                rest = &after[length..];
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn walks_concrete_subtypes_only() {
        let schema =
            "ENTITY IfcRepresentationItem ABSTRACT SUPERTYPE OF (ONEOF(IfcA)); END_ENTITY;\n\
                      ENTITY IfcA SUBTYPE OF (IfcRepresentationItem); END_ENTITY;\n\
                      ENTITY IfcB\n SUBTYPE OF (IfcA); END_ENTITY;\n\
                      ENTITY IfcC ABSTRACT SUPERTYPE OF (IfcD) SUBTYPE OF (IfcA); END_ENTITY;\n\
                      ENTITY IfcOther; END_ENTITY;";
        assert_eq!(concrete_items(schema), ["IfcA", "IfcB"]);
    }
}
