"""Type stubs for the compiled extension. The public API is openbim_ifc."""

import os
from typing import Any, Dict, Iterable, List, Optional, Tuple, Union

class IfcError(Exception):
    code: str

class NativeModel:
    def __init__(self) -> None: ...
    @staticmethod
    def parse(
        data: bytes,
        on_malformed: str = ...,
        check_references: Optional[bool] = ...,
        accept_real_without_point: Optional[bool] = ...,
    ) -> NativeModel: ...
    @staticmethod
    def parse_ifcxml(data: bytes, xsd_profile: Optional[str] = ...) -> NativeModel: ...
    @staticmethod
    def open(
        path: Union[str, "os.PathLike[str]"],
        mapped: bool = ...,
        on_malformed: str = ...,
        check_references: Optional[bool] = ...,
        accept_real_without_point: Optional[bool] = ...,
    ) -> NativeModel: ...
    def write(self) -> bytes: ...
    def write_ifcxml(self, xsd_profile: Optional[str] = ...) -> bytes: ...
    def header(self) -> Dict[str, Any]: ...
    def set_header(self, header: Dict[str, Any]) -> None: ...
    def validate(self, max_findings: Optional[int] = ...) -> Dict[str, Any]: ...
    def unreachable_products(self) -> List[Dict[str, Any]]: ...
    def property_sets(self, id: int) -> List[Dict[str, Any]]: ...
    def resolve_unit(self, measure_type: str, unit: Optional[int] = ...) -> Dict[str, Any]: ...
    def spatial_tree(self) -> Dict[str, Any]: ...
    def classifications(self, id: int) -> List[Dict[str, Any]]: ...
    def material(self, id: int) -> Optional[Dict[str, Any]]: ...
    def systems(self) -> Dict[str, Any]: ...
    def cost(self) -> Dict[str, Any]: ...
    def georeferencing(self) -> List[Dict[str, Any]]: ...
    def __len__(self) -> int: ...
    @property
    def schema(self) -> Optional[str]: ...
    def diagnostics(self) -> List[str]: ...
    def ids(self) -> List[int]: ...
    def ids_of_type(self, type_name: str) -> List[int]: ...
    def ids_of_type_including_subtypes(self, type_name: str) -> List[int]: ...
    def type_of(self, id: int) -> str: ...
    def attributes(self, id: int) -> List[Dict[str, Any]]: ...
    def attribute(self, id: int, index: int) -> Dict[str, Any]: ...
    def set_attribute(self, id: int, index: int, value: Dict[str, Any]) -> Dict[str, Any]: ...
    def add(self, type_name: str, attributes: Iterable[Dict[str, Any]]) -> int: ...
    def remove(self, id: int) -> None: ...
    def dangling_references(self) -> List[Tuple[int, int]]: ...
